name: run-ingest

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

concurrency:
  group: run-ingest-main
  cancel-in-progress: false

jobs:
  run-ingest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger ingest pipeline endpoint
        run: |
          curl --fail --show-error --silent "https://bcso-service-case-docs-e7hfcmdva0gpgphd.centralus-01.azurewebsites.net/run-ingest"
